language: node_js
node_js:
  - "7"
script:
  - APP_ID=$FLIGHT_STAT_APP_ID APP_KEY=$FLIGHT_STAT_APP_KEY ./preprocess.sh testrpc
#  - npm run testrpc &
#  - cd external/ethereum-bridge && npm install && node bridge -a 0 &
#  - ./migselect.sh
#  - ./testselect.sh
#  - npm test -- --network testrpc

sudo: required
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - gcc-4.8
    - g++-4.8
env:
  global:
  - CXX="g++-4.8"
  - CC="gcc-4.8"
  matrix:
  - secure: BL47qmQ9dsTQOidrBJVnIaQSWS7nDVJChp/VZV8+jR3uDbR3f4uJzhvNM4Q+98pKLzbRqe8s9NKbX2u7SGUUvcboWONLAaPrnNHqtmzvci59B+qH7tBhUEkUguucEy9yNplwRuMZV/LtmvKj5Hdpdj61C7QP+dLDZnq5t1fWWqL4bYuiHFHd+Cc5lWZ3heDhCaQ/NtzLbRM2Sm35eZVG1WBFWGnRgKP1dxhUigKkUalPDZZ/G4+QDDFiIxOR5D5kszKqHMATj0HW/ItwBV0q2gkQRbFWtx5yEBBqaZclOJJeo8w4S6dII/EkZRABGmjR0VYJy5IE6P4RMIH9AIlOFXxx9DeZUdxh/By8KQyH1kUJS1+aT+12SaPzK96SWyyhYXrvO/WOe8an/j5Ir+O5E8Cg795pxlf0vYbmJ8NQBxue4wCsJnXziTXH3ctwZJhXgXDHlSXFv5wKStpHLTloWjGypYw0Hh3hGLr6MCNTXfmNY+SxBJV8Ic1ZZiV53KDTu5Poi2DeY7S9Y9DSjnN6hQQpiZHLaqGFPZpyp6v19LgjmbuIyUdq04OLGNs4JdFLOeG0LYh6smJNkSYKyFxxWPQyCuzuaByHqkYU/EVyq/Rx9QpSP9+FSXomhYuUPCLu9hjrC75y8yaKb58Rb/SikkulxY+VsW+V/o7lLKohKjM=
  - secure: ZKmMhMYJTiLT8VFGZDSc7C6xdqXIJkfK8Y1tsXAC/VIDK1vAqXlR+7Klyow4AMnIG1xtQbefGMCTYU5kA1XQFH34DOpRIT3hpp56av25vtskIvZj8hW5XpTXFnTj2OX5QpwgMWq/YFdpA/+wcaW5VhNpqQOhK71mDkvpk2iA/rRqd3p/n2D03dYq9x6WxGLbxHlmZCqTHWSGIzMm2qOOVeMe97mwsNGywK41FTDtDU9qF4noJKqJD/PcXV6l++AnaVTSjEtY9To0BtC8/FwqXKzx7tA+Ha036/BT09ozAsZjWCk1DlonalXfOb5eMI1n06fiup9WbAVyq+MA+KdKt7vvIlid0bhf/9WZNqH8HO15bsA032u9wPW0/uR5fdbc8tplijRSWTjoe4yVEL+bM7jG1+1oxmyv4p7bliWnesvsuu3djv3S0CZPXnITJKomN4jUwnG1TOmxYirvYE1jp7QiGqrxXKr7E2PtnlmVDlpNaUXuNkhrYC10GstMian8luQXx971WDLJxQXekTKFLDetoMRs1fYr+FmWkJIiwnbp0vZYxmJriPZ9FBQVvE7ELoTOXDPXcBgli+h/Non9or8t58uTA6rFgnO4SI0NViQxTl2PL2NAj/hgLtATeR0gtFVOyZa+XXgcnV+L99JBxADNpBGpPu7BobUVeZieYE0=
deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh kovan
    on:
      branch: develop
  - provider: script
    script: deploy.sh mainnet
    on:
      branch: master
