language: node_js
node_js:
  - "7"
script:
  - APP_ID=$FLIGHT_STAT_APP_ID APP_KEY=$FLIGHT_STAT_APP_KEY ./preprocess.sh testrpc
  - npm run testrpc &
  - cd external/ethereum-bridge && npm install && node bridge -a 0 &
  - ./migselect.sh
  - ./testselect.sh
  - npm test -- --network testrpc
deploy:
  - provider: script
    script: deploy.sh kovan
    on:
      branch: develop
  - provider: script
    script: deploy.sh mainnet
    on:
      branch: master
